sudo: required
services:
  - docker

before_install:
  - docker build -t timzehr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true timzehr/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react2"
  env: "DockerReact2-env"
  bucket_name: "elasticbeanstalk-us-east-1-022136424711"
  bucket_path: "docker-react2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
